#                            -*- mode: org; -*-
#
#+TITLE:     README for [[http://openfoam.org/download/source][OpenFOAM-Solidification]]
#+AUTHOR:               The OpenFOAM Foundation
#+DATE:                     15th September 2018
#+LINK:                  http://openfoam.org
#+OPTIONS: author:nil ^:{}
# Copyright (c) 2018 OpenFOAM Foundation.

* About OpenFOAM
  OpenFOAM is a free, open source computational fluid dynamics (CFD) software
  package released by the OpenFOAM Foundation. It has a large user base across
  most areas of engineering and science, from both commercial and academic
  organisations. OpenFOAM has an extensive range of features to solve anything
  from complex fluid flows involving chemical reactions, turbulence and heat
  transfer, to solid dynamics and electromagnetics.

* Copyright
  OpenFOAM is free software: you can redistribute it and/or modify it under the
  terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version.  See the file =COPYING= in this directory or
  [[http://www.gnu.org/licenses/]], for a description of the GNU General Public
  License terms under which you can copy the files.

* Solidification Developments
  This repository contains developments for modeling columnar solidification of
  binary alloys contributed by John Coleman and Dr. Matthew J.M. Krane
  at Purdue University to the OpenFOAM Foundation. These contributions are being
  evaluated and not yet included the main OpenFOAM-dev repository.

  This work includes a solver based on the continuum mixture theory taken from:

  "W.D. Bennon and F.P. Incropera, "A continuum model for momentum, heat and
  species transport in binary solid-liquid phase change systems - 1. Model
  formulation", IJHMT 30 (1987) 2161-2170.

  as well as a test case for the well-known SMACS numerical benchmark:
  [[http://benchmark-solidification.ijl.univ-lorraine.fr]]

  | [[applications/solvers/solidificationFoam][Solidification solver]] | Updated verions of the solidification solver |
  | [[tutorials/multiphase/solidificationFoam/SMACS_I][SMACS Benchmarks]] | Tutorial case for the SMACS numerical benchmark |

* [[https://openfoam.org/resources][Documentation]]
* [[https://cpp.openfoam.org/dev][Source code documentation]]
* [[https://openfoam.org/dev/coding-style-guide][OpenFOAM C++ Style Guide]]
* [[https://bugs.openfoam.org][Reporting bugs in OpenFOAM]]
* [[https://openfoam.org/contact][Contacting the OpenFOAM Foundation]]
