volScalarField& alpha2(fluid.alpha2());

const dimensionedScalar& rho1 = fluid.rho1();
const dimensionedScalar& rho2 = fluid.rho2();

const dimensionedScalar& Cp1 = fluid.Cp1();
const dimensionedScalar& Cp2 = fluid.Cp2();

const dimensionedScalar& kappa1 = fluid.kappa1();
const dimensionedScalar& kappa2 = fluid.kappa2();

const dimensionedScalar& mu1 = fluid.mu1();
const dimensionedScalar& mu2 = fluid.mu2();

const dimensionedScalar& D1 = fluid.D1();
const dimensionedScalar& D2 = fluid.D2();

const dimensionedScalar& DAS = fluid.DAS();

const dimensionedScalar& betaT = fluid.betaT();
const dimensionedScalar& betaC = fluid.betaC();

const dimensionedScalar& TRef = fluid.TRef();
const dimensionedScalar& CRef = fluid.CRef();


