volScalarField& alpha1(fluid.alpha1());
volScalarField& alpha2(fluid.alpha2());

const dimensionedScalar& rho2 = fluid.rho2();

const dimensionedScalar& mu2 = fluid.mu2();

const dimensionedScalar& D2 = fluid.D2();

const dimensionedScalar& DAS = fluid.DAS();

const dimensionedScalar& betaT = fluid.betaT();
const dimensionedScalar& betaC = fluid.betaC();

const dimensionedScalar& TRef = fluid.TRef();
const dimensionedScalar& CRef = fluid.CRef();
